[package]
name = "esimene"
version = "0.1.0"
edition = "2021"

repository = "https://github.com/taunoe/me-learning-rust"
authors = ["Tauno Erik"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
